# To build and deploy to Cloud Run, run from this directory:
# $ gcloud builds submit app --config=cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '.', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/pop-stats/pop-stats:${COMMIT_SHA}', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/pop-stats/pop-stats','-f', 'Dockerfile']
    dir: 'app'
  # Run unit tests
  - name: us-central1-docker.pkg.dev/$PROJECT_ID/pop-stats/pop-stats
    entrypoint: python
    args: ["unit_tests.py"]
    dir: 'app'
  # Verify code with sonarqube
  - name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      /opt/sonar-scanner-4.6.0.2311-linux/launch.sh -X
      '-Dsonar.host.url=https://sonarcloud.io' \
      '-Dsonar.login=$$SONAR_LOGIN' \
      '-Dsonar.projectKey=wrg02_cicd-demo' \
      '-Dsonar.organization=wrg02' \
      '-Dsonar.sources=app/' \
    #- '-X'
    #- '-Dsonar.host.url=https://sonarcloud.io'
    #- '-Dsonar.login=$$SONAR_LOGIN'
    #- '-Dsonar.projectKey=wrg02_cicd-demo'
    #- '-Dsonar.organization=wrg02'
    #- '-Dsonar.sources=app/'
    secretEnv: ['SONAR_LOGIN']     
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/pop-stats/pop-stats:${COMMIT_SHA}']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/pop-stats/pop-stats:latest']
  # Create release in Google Cloud Deploy
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: 
      [
        "beta", "deploy", "releases", "create", "rel-${SHORT_SHA}",
        "--delivery-pipeline", "pop-stats-pipeline",
        "--region", "us-central1",
        "--annotations", "commitId=${REVISION_ID}",
        "--images", "pop-stats=us-central1-docker.pkg.dev/$PROJECT_ID/pop-stats/pop-stats:${COMMIT_SHA}"
      ]
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/sonar_token/versions/4
    env: 'SONAR_LOGIN'
