apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: gcp-e-e-cicd
build:
  artifacts:
  - image: hello-world-python
    context: app
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - k8s/overlays/dev
profiles:
- name: base
  deploy:
    kustomize:
      paths:
      - k8s/base
- name: prod
  deploy:
    kustomize:
      paths:
      - k8s/overlays/prod
- name: staging
  deploy:
    kustomize:
      paths:
      - k8s/overlays/staging
